## Tutorial of Pipeline Run

#### Import Libraries

In [1]:
import os 
import sys
from dotenv import load_dotenv
load_dotenv()
pythonpath = os.getenv('PYTHONPATH')
if pythonpath:
    sys.path.extend(pythonpath.split(os.pathsep))

import dspy
from setfit import SetFitModel
from rich import print
import pandas as pd
import torch
from tqdm import tqdm

import gc
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
from torch import bfloat16
from rich import print
import pickle 

from utils.dspy_qwen2 import (JobPostingModule, 
                              QUESTIONANSWER, 
                              validate_ans)


from utils.prepo import (process_texts,
                         count_words,
                         create_dataframe,
                         filter_and_merge_data)

from langchain_experimental.text_splitter import SemanticChunker
from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain.embeddings import HuggingFaceBgeEmbeddings

/Users/justinvhuang/miniconda3/envs/dspy/lib/python3.11/site-packages/threadpoolctl.py:1214: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

#### Load in Modules from DSPy 
    * uncompiled_fs is faster
    * uncompiled_module is more precise

In [2]:
uncompiled_fs=QUESTIONANSWER('''
                            "position_title" : What is the title of this position?
                            "location" : Where is this position located, including city, state and zip code?
                            "work_arrange" : What is the work arrangement for this position, remote, hybrid, or on-site?
                            "experience" : what are years of experience required for this position?
                            "employment_type" : What is the employment type, full time, part time, or internship?
                            "pay" : What is the pay for this position?
                            "degree" : What is required degree?
                            "certifications" : What certifications or qualifications are required?
                            "required_skills" : What are required skills?
                              ''')
uncompiled_module = JobPostingModule()

#### Load in LLM for DSPy Configuration, Where LLM can be selected among Ollama-Qwen2, Ollama-Gemmma, GPT3.5, and Gemini1.5,

In [3]:
# Ollama 

llm = dspy.OllamaLocal(model='qwen2:latest', max_tokens = 1000, temperature=0.0)
dspy.settings.configure(lm=llm)

# HuggingFace 4-Bit Pre-Quant 

# access_token = ""
# model_name = "google/gemma-7b"
# llm = dspy.HFModel(model=model_name, hf_device_map='auto', token=access_token, model_kwargs= {'temperature': 0.0, 'do_sample': False})
# llm.model=None
# gc.collect()

# bnb_config = BitsAndBytesConfig(
#     load_in_4bit=True,  # 4-bit quantization
#     bnb_4bit_quant_type='nf4',  # Normalized float 4
#     bnb_4bit_use_double_quant=True,  # Second quantization after the first
#     bnb_4bit_compute_dtype=bfloat16  # Computation type
# )
# llm.model=AutoModelForCausalLM.from_pretrained(model_name, quantization_config=bnb_config)
# dspy.settings.configure(lm=llm)

# Hugging Face Post-Quant 4 Bit from Unsloth

# llm = dspy.HFModel(model="unsloth/Qwen2-7B-bnb-4bit", hf_device_map='auto', model_kwargs= {'temperature':0.0,'do_sample': False})
# dspy.settings.configure(lm = llm)

# Connect OpenAI gpt3.5 turbo to DSPy

# api_key=os.getenv('openai_key')
# llm = dspy.OpenAI(model='gpt-3.5-turbo', api_key=api_key)
# dspy.settings.configure(lm=llm)

# Connect to Gemini 1.5 

# gemini_key=os.getenv('gemini_key')
# gemini = dspy.Google("gemini-1.5-flash-latest", api_key=gemini_key)
# dspy.settings.configure(lm=gemini, max_tokens=1024)

#### Load in Example Data From LightCast

In [4]:
df = pd.read_csv("~/data/sample_unclassified_postings.csv", index_col=0)

In [5]:
df[['id', 'body']].head()

,id,body
41066,793b547eed99250aa1b1c3ee30102550f6772919,Vocational Coordinator Kennedy Day School Fran...
17423,05199a06702bfe05fd762f0d4e3b2c464d22e690,"Plastic Surgery Scheduler San Francisco, CA $2..."
112080,fbbd39619c18ea664c3c0a5410eeca9e916b4947,Avionics Expert (SME)\nAvionics Expert (SME)\n...
15434,47a2072651eaf28604ca7e947e78ca6fa7798d61,"Used Car Techs, $21 - $30/hour, Tool Relocatio..."
58984,97e440ec22c524ac8e04ba3cb0216bf7928ce347,"Cyberspace Operations Officer\nFreeport, Illin..."

#### Covnert To Dictionary to Save ID and Body

In [6]:
text_dict = {key:value for key, value in zip(df['id'], df['body'])}

#### Choose Between Semantic Chunking and Recursive Character Text Splitting - Semantic - Less Than 1500 words and less than 8000 Tokens otherwise Recursive Character Text Spltting or else will OOM on 16 GB VRAM

In [7]:
#Semantic Chunking Model
model_name = "nomic-ai/nomic-embed-text-v1.5"
#Set to device to cpu or cuda
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_kwargs = {'device': device, 'trust_remote_code': True}
#normalize to embed faster 
encode_kwargs = {'normalize_embeddings': True}

#Use LangChain to do text embeddings
embeddings = HuggingFaceBgeEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)

/Users/justinvhuang/miniconda3/envs/dspy/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
WARNING:transformers_modules.nomic-ai.nomic-bert-2048.e55a7d4324f65581af5f483e830b80f34680e8ff.modeling_hf_nomic_bert:<All keys matched successfully>

In [8]:
#Semantic Text Spliter
semantic_text_splitter = SemanticChunker(embeddings=embeddings,
                                 breakpoint_threshold_type="percentile",
                                 breakpoint_threshold_amount=5,
                                 )

#Recursive Text Splitter
recursive_text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,
)

#### Split Text and Examine will create a Dictionary Key Value pair with the Key: ID and Value: Job Posting Split into strings within a list
    * please review text-chunking.ipynb there it shows splitting between long job postings and short here we only show semantic chunking for simplicity

In [9]:
split_text_dict = process_texts(text_dict, semantic_text_splitter)

100%|██████████| 20/20 [01:30<00:00,  4.54s/it]

In [10]:
print(len(split_text_dict['793b547eed99250aa1b1c3ee30102550f6772919']))
split_text_dict['793b547eed99250aa1b1c3ee30102550f6772919']

31

["Vocational Coordinator Kennedy Day School Franciscan Children's - Brighton, MA Apply Now Job Details Full-time Estimated: $41,000 - $54,000 a year 9 hours ago Full Job Description 1). Develop life skills curriculum that implements all aspects of life skills and post-school endeavors.",
 '2).',
 'Collaborates with school therapists and specialists to develop job training sites within the school and community.',
 '3).',
 'Consult and collaborate with classroom teachers to integrate life skills and vocational activities in the classroom.',
 '4).',
 'Write and report on vocational and life skills oriented IEP goals.',
 '5).',
 'Attends team meetings, individual education plan meetings (IEP), faculty meetings, coordinators meetings and any other requested meetings.',
 '6).',
 'Prepares and utilizes assessment methodologies to adapt for individual students as appropriate.',
 '7).',
 'Collaborate with families to help implement life skills strategies/routines at home.',
 '8).',
 'Actively participates in students transition into adult services.',
 '9).',
 'Assists students with travel training experiences.10). Encourages students to demonstrate positive work behaviors in a cooperative and productive atmosphere that supports a fundamental work ethic and sense of accomplishment.11).',
 'Assists students in exploring vocational opportunities within their community.12).',
 'Provides families with information and guidance regarding students vocational opportunities.',
 'Assists with transition from school to adult services or other possible employment.',
 '13).',
 'Supervises job coaches and trains other staff who assist in vocational programming.14).',
 'Participates in special educational and vocational skills training activities to advance knowledge and skills.15).',
 'Reinforces and integrates student learning objectives across disciplines.16).',
 'Assists in orientation of new personnel when requested.17).',
 'Assists in screenings of prospective students, as requested.18).',
 'Attends team meetings, Individual Education Plan meetings, faculty meetings, coordinator meetings and any other requested meetings.19).',
 'Writes and manages life skill/vocational related IEP goals.20).',
 'Creates curriculum to collaborate with OT, PT, Speech, O&M, and AT.21).',
 'Support and actively participate with students who transition to adult services.',
 'Apply Now']

#### Load in SetFit Model that was trained on Labeled data

In [11]:
model_name = "setfit_model_v5"
model = SetFitModel.from_pretrained(f"~/ISYE-CSE-MGT-6748-Group-1/models/{model_name}", trust_remote_code = True)

In [12]:
data1 = create_dataframe(split_text_dict)

#### Perform Text Denoising within list of strings

In [13]:
labels = [model.predict([sent]) for sent in tqdm(data1['text'])]

100%|██████████| 468/468 [00:36<00:00, 12.72it/s]

In [14]:
filtered_original_data, new_data, data1_filtered = filter_and_merge_data(data1, labels, df, count_words)

#### Examine Results

In [15]:
new_data[['id','body', 'word_count_original', 'signals_text','word_count_signals', 
              'no_signals_text', 'word_count_no_signal']].head()

,id,body,word_count_original,signals_text,word_count_signals,no_signals_text,word_count_no_signal
0,0138edfb8a54382c8c42fb889632c2e503cb59d1,Assistant Manager - Hotel Parking Operations 6...,924,Assistant Manager - Hotel Parking Operations 6...,446,Manage job preferences anytime in your . You a...,478.0
1,0213598d286572c89f80c7e15722688ed66fd0b3,"Inbound Logistics Coordinator Columbus, OH $20...",513,"Inbound Logistics Coordinator Columbus, OH $20...",421,Yes No Job details Here's how the job details ...,92.0
2,05199a06702bfe05fd762f0d4e3b2c464d22e690,"Plastic Surgery Scheduler San Francisco, CA $2...",384,"Plastic Surgery Scheduler San Francisco, CA $2...",306,Yes No Job details Heres how the job details a...,78.0
3,135d3d0c1f9654d02703bf2dd9dfe08c579ac504,AVP - Underwriting Company: Farm Credit Founda...,892,AVP - Underwriting Company: Farm Credit Founda...,661,We are a growing organization embracing collab...,231.0
4,2efd8e2c7eb393129bff7bd48c942fbd6ac528d0,Pharmacy Technician I Burrell Behavioral Healt...,595,Pharmacy Technician I Burrell Behavioral Healt...,480,"Springfield offers a high quality of life, wit...",115.0

#### More Precise Using ChainOfThought with Hint and Pydantic to Split up Information Search - Takes about 23 Seconds to run

In [16]:
with dspy.context(lm = llm):
    pred = uncompiled_module(job_posting =new_data['signals_text'][0])
    print(pred.info_extracted)

{
    'position_title': 'Assistant Account Manager',
    'location': 'Denver, CO',
    'work_arrangement': 'On-site',
    'experience': '5+ years',
    'employment_type': 'Full-time',
    'pay': '$68K - $75K/year',
    'degree': "Bachelor's",
    'certifications': 'Previous parking industry exp., hospitality focus, supervisory exp., front-line team
oversight, scheduling & payroll skills, Bachelors in business.',
    'required_skills': 'Management, parking ops, customer service, hospitality exp, supervisory skills, scheduling,
payroll, comm., problem-solving, training, admin. duties, safety, finance, policy compliance.'
}

#### Faster but less precise might not keep dictionary format - Takes about 9-10 seconds to run

In [17]:
with dspy.context(lm = llm):
    pred = uncompiled_fs(context =new_data['signals_text'][0])
    print(pred.answer)

{
  "position_title": "Assistant Account Manager",
  "location": "650 15th street, Denver, CO 80202",
  "work_arrangement": "on-site",
  "experience": "previous parking industry experience with a hospitality focus is ideal",
  "employment_type": "full-time",
  "pay": "$68,000 - $75,000 a year",
  "degree": "bachelors degree with a concentration in business is helpful but not required",
  "certifications": "not specified",
  "required_skills": "management experience in the parking, customer service, and/or hospitality industries"
}

#### Store Dictionary to be used for other downstream tasks

In [18]:
with dspy.context(lm = llm):
    pred_dict_precise = {key: uncompiled_module(job_posting = value).info_extracted for key, value in zip(new_data['id'],new_data['signals_text'])}

In [22]:
pred_dict_precise

{'0138edfb8a54382c8c42fb889632c2e503cb59d1': {'position_title': 'Assistant Account Manager',
  'location': 'Denver, CO',
  'work_arrangement': 'On-site',
  'experience': '5+ years',
  'employment_type': 'Full-time',
  'pay': '$68K - $75K/year',
  'degree': "Bachelor's",
  'certifications': 'Previous parking industry exp., hospitality focus, supervisory exp., front-line team oversight, scheduling & payroll skills, Bachelors in business.',
  'required_skills': 'Management, parking ops, customer service, hospitality exp, supervisory skills, scheduling, payroll, comm., problem-solving, training, admin. duties, safety, finance, policy compliance.'},
 '0213598d286572c89f80c7e15722688ed66fd0b3': {'position_title': 'Inbound Logistics Coordinator',
  'location': 'Columbus, OH',
  'work_arrangement': 'On-site',
  'experience': '2-4 years',
  'employment_type': 'Full-time',
  'pay': '$20 - $30 per hour',
  'degree': 'High School Diploma or GED',
  'certifications': "High School Diploma/GED, 1-3 years' logistics exp., Proficient in Microsoft Office.",
  'required_skills': 'Logistics coordination, cost savings, fleet utilization, market rate negotiation, shipper/broker communication, customer needs understanding, project reporting, schedule management, driver liaison, independent judgement, pricing analysis, freight line resolution, professional competence, attention to detail, organizational skills, Microsoft Office proficiency.'},
 '05199a06702bfe05fd762f0d4e3b2c464d22e690': {'position_title': 'Plastic Surgery Scheduler',
  'location': 'San Francisco, CA',
  'work_arrangement': 'On-site',
  'experience': '3-5 years',
  'employment_type': 'Full-time, Contract',
  'pay': '$20 - $23 per hour',
  'degree': 'High school',
  'certifications': 'Medical Terminology, Customer Service, Plastic Surgery Experience, Computer Skills',
  'required_skills': 'Customer service, medical terminology, computer skills, plastic surgery experience.'},
 '135d3d0c1f9654d02703bf2dd9dfe08c579ac504': {'position_title': 'AVP Underwriting',
  'location': 'Turlock, California',
  'work_arrangement': 'Hybrid',
  'experience': '8+ years',
  'employment_type': 'Full-time',
  'pay': '$80,075 - $125,117 annual',
  'degree': "Bachelor's",
  'certifications': 'Certified Agricultural Credit Manager (CACM)',
  'required_skills': 'Analyzing loans, evaluating applications, interviewing applicants, preparing financial statements, inputting data, reviewing credit reports, determining approvals, managing portfolios, conducting inspections, providing training.'},
 '2efd8e2c7eb393129bff7bd48c942fbd6ac528d0': {'position_title': 'Pharmacy Technician',
  'location': 'Springfield, MO',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Full-time',
  'pay': '$31,600 - $40,000 annually',
  'degree': 'High School Diploma',
  'certifications': 'Pharmacy Technician License',
  'required_skills': 'Pharmacy operations, computer proficiency, strong communication, collaboration, customer service, HIPAA compliance.'},
 '32964b778f0773673966bfe87898a56941ecec33': {'position_title': 'Bookkeeper / Accountant',
  'location': 'Ypsilanti, MI',
  'work_arrangement': 'On-site',
  'experience': '3+ years',
  'employment_type': 'Full-time',
  'pay': '$37.18-$38.67 hourly',
  'degree': "Bachelor's Degree",
  'certifications': "Bachelor's in Accounting, Business Administration, Finance, CPA",
  'required_skills': 'Accounting, Finance, Bookkeeping, Financial Reporting, Budget Management, Data Analysis, Auditing, Microsoft Excel, Customer Service, Team Leadership.'},
 '3edcdc50fb89c4f95dbc24103ca18753510efae6': {'position_title': 'Senior Cyber Security Engineer',
  'location': 'Helena, MT',
  'work_arrangement': 'Remote',
  'experience': '5+ years',
  'employment_type': 'Full-time',
  'pay': 'Not specified',
  'degree': "Bachelor's",
  'certifications': 'OSCP, CISSP',
  'required_skills': 'Penetration testing, web app sec, Nmap, Burpsuite, SQLMap, network analysis, PKI, cybersecurity tools, vulnerability management, assessment methods, countermeasures planning, security standards, deployment security, trend awareness, comm skills, multitasking, industry certs.'},
 '47a2072651eaf28604ca7e947e78ca6fa7798d61': {'position_title': 'Used Car Technician',
  'location': 'Merrillville, IN',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Full-time',
  'pay': '$21 - $30/hour',
  'degree': 'High School',
  'certifications': "Used car technician repair experience, valid driver's license, insurance, high school diploma.",
  'required_skills': 'Automotive inspections, diagnostics, maintenance, repairs, tool usage, communication, organization, teamwork, positive attitude, work ethic, valid license, high school diploma.'},
 '793b547eed99250aa1b1c3ee30102550f6772919': {'position_title': 'Vocational Coordinator',
  'location': 'Brighton, MA',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Full-time',
  'pay': '$41,000 - $54,000 a year',
  'degree': 'High School',
  'certifications': 'Life Skills Curriculum Developer, Job Training Site Coordinator, IEP Goals Writer, Transition Services Advisor',
  'required_skills': 'Develops life skills curriculum, collaborates with therapists, integrates activities in classrooms, writes IEP goals, attends meetings, assesses students, implements strategies at home, supports student transitions, teaches work ethics, explores vocational opportunities, provides employment guidance, supervises job coaches, reinforces learning objectives, assists new personnel, screens prospective students, manages IEP goals, creates collaborative curriculum, supports adult services transition.'},
 '8a5440f8b7a612047ff75a257a84c3ba75e1733d': {'position_title': 'Assistant Construction Project Manager',
  'location': 'Wicker Park, IL',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Contract',
  'pay': '$24/hr',
  'degree': 'Not specified',
  'certifications': 'Not Specified',
  'required_skills': 'PDF management, Excel proficiency, Construction knowledge, Project coordination'},
 '9577824d69e9afff59aa7f381039d7d5dc1becdc': {'position_title': 'Medical Receptionist',
  'location': 'Stony Brook, NY',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Full-time',
  'pay': '$19.78-$24.72 hourly',
  'degree': 'High School',
  'certifications': 'High school diploma/GED',
  'required_skills': 'High school diploma/GED, 6 months medical receptionist exp., proficiency in EMR, practice management systems.'},
 '97e440ec22c524ac8e04ba3cb0216bf7928ce347': {'position_title': 'Cyberspace Operations Officer',
  'location': 'Freeport, Illinois, USA',
  'work_arrangement': 'On-site',
  'experience': 'Not specified.',
  'employment_type': 'Full Time',
  'pay': 'Not specified.',
  'degree': "Bachelor's degree",
  'certifications': 'Single Scoped Background Investigation (SSBI), Officer Training School (OTS), Air Force Academy (AFA), AFROTC.',
  'required_skills': "Cybersecurity, Electronics Theory, IT Knowledge, Telecommunications, Cryptography, Vulnerability Assessment, Exploitation Techniques, Supervisory Systems, Mathematics, Computer Science, Bachelor's Degree, Background Check, Officer Training."},
 '98d8d320bd765c15161d3546d7fc995629ace908': {'position_title': 'Front Desk Agent',
  'location': 'Miami Beach, FL',
  'work_arrangement': 'On-site',
  'experience': 'Not specified',
  'employment_type': 'Full-time',
  'pay': 'Competitive wages',
  'degree': 'High School',
  'certifications': 'High school diploma/GED, one year experience, basic computer skills.',
  'required_skills': 'Customer service, communication, problem-solving, basic computer skills, high school diploma/GED, hotel experience.'},
 '994d178e095b430a82278d170eb4e2304d93b129': {'position_title': 'Rise Coordinator',
  'location': 'Hartford, CT 06103',
  'work_arrangement': 'On-site',
  'experience': '1-4 years',
  'employment_type': 'Full-time',
  'pay': '$62,033',
  'degree': "Bachelor's",
  'certifications': 'Excellent oral and written comm., Strong IT literacy (MS Office), Advanced student services knowledge, Admissions/onboarding understanding, Fast-paced environment skills, Multitasking, Innovative problem-solving.',
  'required_skills': 'Strong comm., IT literacy, multitasking, problem-solving, student services exp., fast-paced adaptability.'},
 'a796d078d8dec209343b32d978172a363eb0bf5c': {'position_title': 'CNC Programmer',
  'location': 'Schererville, IN',
  'work_arrangement': 'On-site',
  'experience': '4+ years',
  'employment_type': 'Full-time',
  'pay': '$25-$32 per hour',
  'degree': 'High School',
  'certifications': 'CNC Programming, Dial Calipers, Blueprint Reading, Math Skills',
  'required_skills': 'CNC programming, 3D surfacing, machine operation, math skills, blueprint interpretation, computer literacy, communication, teamwork, problem-solving, tool use.'},
 'ad48ed269acc7331aec8cf0444a690663929c8c6': {'position_title': 'The title of the job or position described in the text is "Child and Youth Behavioral Health Counselor".',
  'location': 'The job location specified in the document is within the United States. This conclusion is drawn from the requirement for counselors to hold a valid unrestricted counseling license from a state, District of Columbia, US territory, or commonwealth that grants authority to provide counseling services as an independent practitioner. The condition that counselors must be licensed or certified in the state where the client is receiving services further indicates that the job could be located anywhere within the United States, including on military installations across different states.',
  'work_arrangement': "Job Title: Military Child & Youth Counselor\n\n**Responsibilities:**\n1. **Counseling Services:** Provide individual, group, and family counseling sessions for children and youth at various locations including schools and military installations.\n2. **Parent Training:** Offer guidance and training to parents on supporting their children's mental health and development.\n3. **Health & Wellness Presentations:** Conduct presentations focused on health and wellness topics relevant to children and youth.\n4. **Community Engagement:** Participate in community activities such as health fairs, base events, and school functions to promote services and resources for children and families.\n5. **Data Reporting:** Regularly enter counselor activity data through smartphone or web applications while maintaining confidentiality.\n\n**Job Location:**\nThe job is located on military installations or related worksites where services are provided to children and youth associated with the military community. This includes schools, offices, and various locations within military bases.\n\n**Work Environment:**\n- **Remote Activities:** Data entry and supervision tasks can be performed remotely.\n- **On-Site Interactions:** Regular interactions occur in educational settings and military environments.\n\n**Requirements:**\n1. **U.S. Citizenship & Fluency in English:** Candidates must be U.S. citizens who are fluent in English.\n2. **Driver's License:** Possess a valid driver's license, with the option for a military vehicle operator's permit for commercial sedans if required at specific locations.\n3. **Background Checks:** Must pass NACI clearance, IRC check, and FBI fingerprinting to ensure suitability for working with sensitive information and children.\n4. **Health Requirements:** Depending on location, candidates may need to complete specific vaccinations or health clearances as per military guidelines.\n\n**Skills Required:**\n- Strong interpersonal skills\n- Empathy for military families\n- Cultural sensitivity\n- Proficiency in handling sensitive information while maintaining confidentiality",
  'experience': "The job posting requires a minimum of 2 years of post-masters supervised clinical experience. This means the candidate must have completed at least 2 years of practical, supervised work in their field after obtaining their master's degree. This experience is crucial as it ensures that the individual has hands-on knowledge and skills necessary for providing effective counseling services to military members and their families. The experience should be directly related to mental health or a relevant field such as social work, psychology, marriage/family therapy, or counseling.",
  'employment_type': "The information provided outlines several key aspects of working as a School-Based Youth Counselor in a military context:\n\n1. **Roles and Responsibilities**: The counselor is tasked with providing guidance to parents, delivering health and wellness presentations, participating in school activities, maintaining confidentiality through daily data entry, establishing relationships within the community focused on children's welfare, partnering with Child and Youth Behavioral Health services, building professional relationships with facility Point of Contact (POC), managing duty to warn situations according to DoD protocol, communicating regularly with supervisors, responding to critical incidents, participating in training sessions, and engaging in quality improvement activities.\n\n2. **Qualifications**: The role requires a Master's degree from an accredited graduate program in fields such as social work, psychology, marriage/family therapy, or counseling. Fluency in English is necessary, along with passing background checks including NACI clearance, Installation Records Check (IRC), criminal background check, and FBI fingerprints check. A valid US state vehicle operator’s license is also required unless waived by the Fedsim Cor.\n\n3. **Employment Type**: The nature of this role suggests it could be full-time or part-time depending on the specific needs of the military installation or facility where the counselor works. It might also involve contract-based employment, internships, or apprenticeships based on the context provided.\n\n4. **Additional Requirements**: Beyond professional qualifications and licensing, counselors must demonstrate understanding, sensitivity, and empathy towards service members and their families. They are expected to work effectively with diverse racial, ethnic, and socioeconomic backgrounds. Compliance with site-specific requirements at designated locations is also essential, which may include health-related protocols such as vaccinations or other medical screenings.\n\nThis role combines professional counseling skills with the unique demands of a military environment, requiring not only expertise in youth development and mental health but also an understanding of military culture and operational contexts.",
  'pay': 'The provided information does not explicitly mention the pay rate, hourly wage, or annual salary for this job. To determine these details, you would need to look at specific job postings, company policies, or industry standards related to similar roles and responsibilities. Factors such as location, experience level, education requirements, and current market rates can influence the compensation package offered for a position like this one in parent training, health and wellness presentations, and counseling services focused on children and youth.\n\nHint: The dollars per hour or salary for the year or pay',
  'degree': "Master's Degree",
  'certifications': 'Valid Unrestricted Counseling License',
  'required_skills': "The required skills and qualifications for performing the job, based on the information provided, include:\n\n1. **Physical Environment Adaptability**: Ability to work in a variety of physical environments, including military installations or related worksites.\n2. **Immunization Compliance**: Need to have certain immunizations or vaccinations as per site-specific requirements and provide proof of receipt.\n3. **US Citizenship Verification**: Must prove US citizenship status.\n4. **Fluency in English**: Fluent communication skills in English are necessary.\n5. **Cultural Sensitivity**: Understanding, sensitivity, and empathy for service members and their families from diverse racial, ethnic, and socioeconomic backgrounds.\n6. **Background Checks**: Ability to pass a National Agency Check and Inquiries (NACI) clearance, Installation Records Check (IRC), criminal background check, and FBI fingerprints check.\n7. **Driver's License**: Possession of a valid U.S. state vehicle operator's license unless waived by the Fedsim Cor for counseling support at government locations.\n8. **Training and Guidance Skills**: Providing training and guidance to schools, summer camps, parents, conducting health and wellness presentations, participating in health fairs and base activities focused on children and youth.\n9. **Data Management**: Entering counselor activity data through smartphone or web application while maintaining confidentiality.\n10. **Accessibility**: Maintaining a presence in the school environment being available to children, youth, and staff.\n11. **Line of Sight Protocol**: Adhering to line of sight protocol when working with children (another adult must be able to see the counselor and child at all times).\n12. **Community Resource Networking**: Establishing and maintaining relationships with community resources focused on children and youth, providing appropriate linkages.\n13. **Child and Youth Behavioral Services**: Partnering with Point of Contact (POC) for Child and Youth Behavioral Health services.\n14. **Professional Qualifications**: Master's degree in mental health related fields such as social work or psychology.\n15. **Diverse Background Working**: Ability to work effectively with diverse racial, ethnic, and socioeconomic backgrounds.\n\nThese skills collectively ensure that the individual is capable of fulfilling the job responsibilities efficiently and effectively within a complex environment requiring both professional expertise and interpersonal sensitivity."},
 'da03a1a1069467000d253e27ed6234524803e32a': {'position_title': 'Group Exercise Instructor',
  'location': 'Wellesley, MA 02481',
  'work_arrangement': 'On-site',
  'experience': 'Not Specified',
  'employment_type': 'Full time',
  'pay': '$63.20 per day',
  'degree': 'Not Specified',
  'certifications': 'Certified Group Exercise Instructor',
  'required_skills': 'Teaching, fitness instruction, group dynamics, communication, patience, adaptability.'},
 'ebe24c557484e0c1982156fe54947c387bb3face': {'position_title': 'Experience Representative/Teller',
  'location': 'Des Moines, IA',
  'work_arrangement': 'On-site',
  'experience': '1-2 years',
  'employment_type': 'Full-time',
  'pay': '$16 - $17 an hour',
  'degree': 'High School Diploma or GED',
  'certifications': 'High School Diploma/GED, Cash Handling, Communication Skills',
  'required_skills': 'Customer service, communication, cash handling, banking knowledge, product promotion, regulatory compliance, digital banking, scheduling.'},
 'ef0f5d2fbae1054672f8df41b5caad688b17db99': {'position_title': 'Paralegal with Military Experience',
  'location': 'Alexandria, VA',
  'work_arrangement': 'Remote Hybrid',
  'experience': '2+ years',
  'employment_type': 'Full-time',
  'pay': 'Not specified',
  'degree': 'Bachelors or Paralegal Certification',
  'certifications': 'TS/SCI license, Paralegal certification, Litigation discovery software proficiency.',
  'required_skills': 'US citizenship, TS/SCI clearance, 2+ years military/jag paralegal exp., Assoc./Bachelors or cert., Travel ability, Fast typing, Transcription, Discretion, Research skills, Paralegal knowledge, Litigation software proficiency, MS Office & Adobe PDF.'},

In [19]:
with open('~/ISYE-CSE-MGT-6748-Group-1/data/pred_dict_precise.pickle', 'wb') as handle:
    pickle.dump(pred_dict_precise, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [20]:
with dspy.context(lm = llm):
    pred_dict_fast = {key: uncompiled_fs(context = value).answer for key, value in zip(new_data['id'],new_data['signals_text'])}

In [23]:
pred_dict_fast

{'0138edfb8a54382c8c42fb889632c2e503cb59d1': '{\n  "position_title": "Assistant Account Manager",\n  "location": "650 15th street, Denver, CO 80202",\n  "work_arrangement": "on-site",\n  "experience": "previous parking industry experience with a hospitality focus is ideal",\n  "employment_type": "full-time",\n  "pay": "$68,000 - $75,000 a year",\n  "degree": "bachelors degree with a concentration in business is helpful but not required",\n  "certifications": "not specified",\n  "required_skills": "management experience in the parking, customer service, and/or hospitality industries"\n}',
 '0213598d286572c89f80c7e15722688ed66fd0b3': '{\n    "position_title": "Inbound Logistics Coordinator",\n    "location": "Columbus, OH",\n    "work_arrange": "On-site",\n    "experience": "1-3 years\' experience",\n    "employment_type": "Full-time",\n    "pay": "$20 - $30 an hour",\n    "degree": "High school diploma or equivalent; preferred: 2-4-year degree in supply chain, logistics, transportation management",\n    "certifications": "Not specified",\n    "required_skills": "Understanding of cube size and weight restrictions for loading; excellent attention to detail; good organizational skills; proficient in Microsoft Office systems"\n}',
 '05199a06702bfe05fd762f0d4e3b2c464d22e690': '{\n  "position_title": "Plastic Surgery Scheduler",\n  "location": "San Francisco, CA",\n  "work_arrange": "On-site",\n  "experience": "3 years for customer service and medical terminology; 1 year for plastic surgery experience preferred",\n  "employment_type": "Full-time, Contract",\n  "pay": "$20 - $23 per hour",\n  "degree": "High school diploma or equivalent required",\n  "certifications": "Not specified",\n  "required_skills": "Experience in aesthetics industry, phone skills, medical terminology, customer service"\n}',
 '135d3d0c1f9654d02703bf2dd9dfe08c579ac504': 'Position Title: AVP - Underwriting\n\nLocation: Livermore, California\n\nWork Arrangement: Part-time remote/hybrid\n\nExperience Required: At least eight years of progressively responsible banking or related agricultural lending experience\n\nEmployment Type: Full time (Note: The description mentions part-time remote/hybrid work arrangement but also requires significant experience and responsibilities typically associated with a full-time role)\n\nPay Range: Minimum $80,075.03 - max $125,117.24 annual\n\nDegree Required: BA/BS degree with emphasis on agribusiness, business administration, or equivalent\n\nCertifications Not Mentioned\n\nRequired Skills:\n- Ability to perform basic office tasks and work in a typical office setting\n- Strong written and verbal communication skills\n- Proficiency in using PC including word-processing, email, and electronic spreadsheet software',
 '2efd8e2c7eb393129bff7bd48c942fbd6ac528d0': '{\n  "position_title": "Pharmacy Technician I",\n  "location": "Springfield, MO",\n  "work_arrange": "On-site",\n  "experience": "No specific years mentioned",\n  "employment_type": "Full-time",\n  "pay": "$31.6k - $40k a year",\n  "degree": "High school diploma or GED",\n  "certifications": "Pharmacy Technician License in good standing with appropriate board",\n  "required_skills": "Customer service, pharmacy technician license, high school diploma or GED, computer skills"\n}',
 '32964b778f0773673966bfe87898a56941ecec33': '{\n  "position_title": "Bookkeeper / Accountant",\n  "location": "Ypsilanti, MI 48198",\n  "work_arrange": "On-site",\n  "experience": "3 years of accounting experience required",\n  "employment_type": "Full-time",\n  "pay": "$37.18 - $38.67 an hour",\n  "degree": "Bachelor\'s degree in Accounting, Business Administration, or Finance",\n  "certifications": "Knowledge of the principles and practices of government entity accounting",\n  "required_skills": "Computerized accounting system knowledge"\n}',
 '3edcdc50fb89c4f95dbc24103ca18753510efae6': '{\n  "position_title": "Senior Cyber Security Engineer",\n  "location": "Helena, MT",\n  "work_arrangement": "100% remote",\n  "experience": "5 years of relevant experience required; or 4 years with a bachelor\'s degree",\n  "employment_type": "Full time",\n  "pay": "Not Specified",\n  "degree": "Bachelor\'s degree in Information Systems/Technology, Engineering discipline preferred",\n  "certifications": "OSCP and CISSP industry certifications highly desired",\n  "required_skills": "Knowledge of penetration testing tools like burpsuite, nmap, appscan; experience with web application security assessments and penetration tests"\n}',
 '47a2072651eaf28604ca7e947e78ca6fa7798d61': '{\n  "position_title": "Used Car Technician",\n  "location": "1794 w 81st ave, Merrillville, IN 46410",\n  "work_arrangement": "On-site",\n  "experience": "Prefered used car technician repair experience",\n  "employment_type": "Full time",\n  "pay": "$21 - $30/hour based on experience",\n  "degree": "High school diploma or equivalent",\n  "certifications": "No specific certifications mentioned, but automotive industry certifications may be preferred",\n  "required_skills": "Good communication and organizational skills, positive attitude, good work ethic"\n}',
 '793b547eed99250aa1b1c3ee30102550f6772919': '{\n  "position_title": "Vocational Coordinator",\n  "location": "Brighton, MA",\n  "work_arrange": "On-site",\n  "experience": "Not Specified",\n  "employment_type": "Full-time",\n  "pay": "$41,000 - $54,000 a year",\n  "degree": "Not Specified",\n  "certifications": "Not Specified",\n  "required_skills": [\n    "Curriculum Development",\n    "Collaboration with Therapists and Specialists",\n    "IEP Writing and Reporting",\n    "Assessment Methodologies",\n    "Transition Planning",\n    "Life Skills Integration",\n    "Vocational Opportunities Exploration",\n    "Family Engagement",\n    "Positive Work Behavior Support"\n  ]\n}',
 '8a5440f8b7a612047ff75a257a84c3ba75e1733d': '{\n  "position_title": "Assistant Construction Project Management",\n  "location": "Wicker Park",\n  "work_arrange": "On-site",\n  "experience": "Not Specified",\n  "employment_type": "Contract",\n  "pay": "$24/hr",\n  "degree": "Not Specified",\n  "certifications": "Principals only",\n  "required_skills": "Working with PDFs and Excel"\n}',
 '9577824d69e9afff59aa7f381039d7d5dc1becdc': "The position title is Front Desk Medical Receptionist. This position is located in Stony Brook, NY 11790. The work arrangement for this position is on-site. The required experience includes at least 6 months of experience working as a medical receptionist in a high volume physician practice and preferably 1 year of clerical experience. The employment type offered is full time. The pay rate is not specified in the provided information. A high school diploma or GED is required for this position, while it's preferred that candidates have graduated from an accredited medical office administration program. Proficiency in using an Electronic Medical Record (EMR) and a practice management system are also required skills for this role.",
 '97e440ec22c524ac8e04ba3cb0216bf7928ce347': '{\n  "position_title": "Cyberspace Operations Officer",\n  "location": "Freeport, Illinois, USA",\n  "work_arrange": "On-site",\n  "experience": "Minimum education - Bachelor\'s degree",\n  "employment_type": "Full time",\n  "pay": "Not Specified",\n  "degree": "Bachelor\'s degree in Computer and Information Sciences, Engineering, Mathematics, Computer Science, Management Information Systems or related disciplines",\n  "certifications": "Completion of undergraduate cyberspace training, mission qualification training in specialty area, current single scoped background investigation (SSBI), completion of Officer Training School (OTS), Air Force Academy (AFA) or Air Force Reserve Officer Training Corps (AFROTC)",\n  "required_skills": "Knowledge of electronics theory, information technology, telecommunications and supervisory and control systems including cryptography, vulnerability assessment and exploitation techniques"\n}',
 '98d8d320bd765c15161d3546d7fc995629ace908': '{\n  "position_title": "Front Desk Agent",\n  "location": "860 Ocean Drive, Miami Beach, FL 33139",\n  "work_arrange": "On-site",\n  "experience": "One year previous experience",\n  "employment_type": "Full-time",\n  "pay": "Competitive wages",\n  "degree": "High school graduate or GED",\n  "certifications": "None specified",\n  "required_skills": "Basic computer skills"\n}',
 '994d178e095b430a82278d170eb4e2304d93b129': "The required skills for the position described include:\n\n1. **Excellent oral and written communication:** This skill is crucial for effectively interacting with students, colleagues, and other stakeholders to provide clear guidance and information.\n\n2. **Strong information technology literacy (e.g., Microsoft Office):** Proficiency in using common software tools ensures that tasks related to data management, record-keeping, and communication can be handled efficiently.\n\n3. **Ability to work in a fast-paced environment:** The role involves managing multiple responsibilities simultaneously, requiring the ability to handle pressure and meet deadlines without compromising quality.\n\n4. **Multitasking ability:** With various duties such as advising students on registration periods, working with admissions, and handling placement testing, the capacity to manage several tasks concurrently is essential.\n\n5. **Innovative problem-solving skills related to student registration and college attendance issues:** This skill enables proactive solutions to challenges that may arise in managing student enrollment and participation.\n\nThese skills collectively ensure that the individual can effectively contribute to the smooth operation of the admissions process and support students' academic success at the Connecticut State Community College.",
 'a796d078d8dec209343b32d978172a363eb0bf5c': '{\n  "position_title": "CNC Programmer",\n  "location": "Schererville, IN",\n  "work_arrange": "On-site",\n  "experience": "Minimum 2 years for CNC Programming, Minimum 4 years for setting up and operating CNC machines",\n  "employment_type": "Full-time",\n  "pay": "$25.00 - $32.00 per hour",\n  "degree": "Not Specified",\n  "certifications": "Pass pre-employment background and drug screen, Strong computer skills",\n  "required_skills": "Strong math skills, Ability to read and use dial calipers and basic machinist tools, Ability to analyze information provided in blueprints, Problem solving skills"\n}',
 'ad48ed269acc7331aec8cf0444a690663929c8c6': "Position Title: School Counselor or similar role\n\nLocation: Various locations across the United States (DODEA schools, community schools, summer camps)\n\nWork Arrange: On-site\n\nExperience: Several years of professional experience in counseling or related fields\n\nEmployment Type: Full time\n\nPay: Not specified\n\nDegree: Bachelor’s degree or higher in relevant field\n\nCertifications: NACI clearance, IRC check, criminal background check, FBI fingerprints check\n\nRequired Skills: Understanding and empathy for service members' families, ability to work with diverse populations, fluency in English",
 'da03a1a1069467000d253e27ed6234524803e32a': '{\n  "position_title": "Group Exercise Instructor",\n  "location": "Wellesley, MA 02481",\n  "work_arrange": "On-site",\n  "experience": "Not specified",\n  "employment_type": "Full time",\n  "pay": "$63.20 per day",\n  "degree": "Not specified",\n  "certifications": "Not specified",\n  "required_skills": "Group exercise instruction"\n}',
 'ebe24c557484e0c1982156fe54947c387bb3face': '{\n  "position_title": "Experience Representative",\n  "location": "Des Moines, IA",\n  "work_arrange": "On-site",\n  "experience": "1 year",\n  "employment_type": "Full-time",\n  "pay": "$16 - $17 an hour",\n  "degree": "High school diploma or GED",\n  "certifications": "None specified",\n  "required_skills": "Customer service, cash handling, communication skills"\n}',
 'ef0f5d2fbae1054672f8df41b5caad688b17db99': '{\n  "position_title": "Paralegal with Military Experience",\n  "location": "Alexandria, VA 22303",\n  "work_arrange": "Remote and On-site (with occasional travel)",\n  "experience": "Minimum of 2 years in a military/JAG environment",\n  "employment_type": "Full-time",\n  "pay": "Not Specified",\n  "degree": "Associates, Bachelor\'s degree or Paralegal certification",\n  "certifications": "TS/SCI license (current active or previous clearance preferred)",\n  "required_skills": "Factual and legal research skills, proficiency in litigation discovery software and MS Office Suite"\n}',
 'fbbd39619c18ea664c3c0a5410eeca9e916b4947': "Position Title: The position title is not explicitly stated in the provided information but could be a technical or managerial role focused on cybersecurity, system engineering, and risk management for weapon systems within the defense sector.\n\nLocation: The location of the position is not specified by city, state, or zip code. It suggests that the position can be based anywhere due to the nature of remote work being implied in roles requiring flexibility and consultation across various tasks and projects.\n\nWork Arrange: The work arrangement is likely hybrid/on-site with some flexibility for meetings and project management needs. This implies a mix of on-site presence for critical interactions and off-site work for independent tasks.\n\nExperience: While not explicitly stated, the position requires experience with USAF weapon systems acquisition, indicating that candidates should have relevant background in defense or aerospace industry projects.\n\nEmployment Type: Regular full-time employment is specified.\n\nPay: The pay rate for this position is not provided within the text.\n\nDegree: A bachelor's degree is required as a minimum educational qualification.\n\nCertifications/Qualifications: No specific certifications are mentioned, but candidates should have experience and skills in cybersecurity, system engineering, risk management, and defense industry projects. Additionally, they must be able to perform background investigations as part of employment requirements and adhere to equal opportunity employer policies.\n\nRequired Skills:\n- Experience with cybersecurity, system engineering, and risk management.\n- Knowledge of weapon systems and their acquisition processes within the US military context.\n- Ability to conduct background investigations as required by employment.\n- Understanding of equal opportunity employer practices."}

In [21]:
with open('~/ISYE-CSE-MGT-6748-Group-1/data/pred_dict_fast.pickle', 'wb') as handle:
    pickle.dump(pred_dict_fast, handle, protocol=pickle.HIGHEST_PROTOCOL)