## GPT 3.5-Turbo DSPy

In [2]:
import dspy
import pandas as pd
import os
import json

# Set up a basic teleprompter forcompiling the program.
from dspy.teleprompt import BootstrapFewShot

# Set up the `evaluation` function. 
from dspy.evaluate.evaluate import Evaluate

#### Load in Training Examples

In [28]:
# import data from 20 manual examples as training and 50 gpt examples as validation
train_examples=pd.read_csv('~/20 Manual Labeling.csv')
print(train_examples.shape)
train_examples.head(3)

dev_examples=pd.read_csv('~/50examples_for_DSPy_withJson.csv')
print(dev_examples.shape)
dev_examples.head(3)

(20, 16)
(46, 16)

                    id                 body  min_edulevels_name employment_type_name  min_years_experience remote_type_name  salary_to        city_name      state_name           title_name specialized_skills_name  certifications_name   common_skills_name          naics2_name            onet_name            pred_json
0  18ec1d38a8acc34f...  Derrickhand, Buc...  High school or GED  Full-time (> 32 ...                  1.0            [None]        NaN   Buckhannon, WV   West Virginia         Derrickhands  ['Well Services'...     ['CDL Class B Li...  ['Customer Servi...  Unclassified Ind...  Roustabouts, Oil...  {\n    "position...
1  0b8c421fca565f14...  Business Relatio...  High school or GED  Full-time (> 32 ...                  4.0            [None]    45000.0   Mount Airy, NC  North Carolina  Business Relatio...  ['Public Adminis...                      []  ['Presentations'...  Unclassified Ind...  Rehabilitation C...  {\n    "position...
2  256704ef9f689ef8...  Pharmacy Technic...  High school or GED  Full-time (> 32 ...                  NaN            [None]    39520.0  San Quentin, CA      California  Pharmacy Technic...  ['Medical Prescr...     ['Certified Phar...  ['Customer Servi...  Unclassified Ind...  Pharmacy Technic...  {\n    "position...

#### Format Training Examples to DSPy format

In [35]:
# set up training dataset and validation dataset
train_results = list(train_examples['pred_json'])
train_contents=list(train_examples['body'])
print(len(train_results),len(train_contents))

dev_results = list(dev_examples['pred_json'])
dev_contents=list(dev_examples['body'])
print(len(dev_results),len(dev_contents))

train_example_list=[dspy.Example(context=content, answer=result) for content, result in zip(train_contents, train_results)]
dev_example_list=[dspy.Example(context=content, answer=result) for content, result in zip(dev_contents, dev_results)]


trainset=train_example_list
devset=dev_example_list[:5] # just use first 5 examples for testing for now

# 'body' field is the input. 'pred_json'are labels and/or metadata.
trainset = [x.with_inputs('context') for x in trainset]
devset = [x.with_inputs('context') for x in devset]

print(len(trainset),len(devset))

20 20
46 46
20 5

#### Connect to Open AI API Key and create model Signature and Module

In [36]:
# Connect OpenAI gpt3.5 turbo to DSPy
api_key=os.getenv('openai_key')
turbo = dspy.OpenAI(model='gpt-3.5-turbo', api_key=api_key)
dspy.settings.configure(lm=turbo)


# create signature for input and output
class GenerateAnswer(dspy.Signature):
    """Answer questions with short factoid answers."""

    context = dspy.InputField(desc="contain relevant facts")
    question = dspy.InputField(desc="unique possible questions")
    answer = dspy.OutputField(
    desc="Answers should be a JSON object containing key-value pairs, with the keys being: 'position_title', 'location', 'work_arrangement', 'experience', 'employment_type', 'pay', 'degree_certification', and 'required_skills'. The values should be between 1 and 30 words. If you do not know the answer, just state 'Not Specified'"
)

# Create module using dspy module
class QUESTIONANSWER(dspy.Module):
    def __init__(self,question):
        super().__init__()
        self.generate_answer = dspy.ChainOfThought(GenerateAnswer, max_tokens=400)
        self.question=question

    def forward(self, context):
        question=self.question
        pred = self.generate_answer(context=context, question=question)
        return dspy.Prediction(context=context,answer=pred.answer)


uncompiled=QUESTIONANSWER('''
                             1. What is the title of this position?
                             2. Where is this position located, including city, state and zip code?
                             3. What is the work arrangement for this position, remote, hybrid, or on-site?
                             4. what are years of experience required for this position?
                             5. What is the employment type, full time, part time, or internship?
                             6. What is the pay for this position?
                             7. What is required degree or certification?
                             8. What are required skills?
                              ''')

#### Validate Uncompiled vs Compiled

In [38]:
# Validation logic: check that the predicted answer is correct using 'exact_match'
    # we perhaps need to create our own metric or use another LLM as judge
def validate_answer(example, pred, trace=None):
    answer_EM = dspy.evaluate.answer_exact_match(example, pred)
    return answer_EM

teleprompter = BootstrapFewShot(metric=validate_answer)

# Compile
compiled = teleprompter.compile(uncompiled, trainset=trainset)

evaluation = Evaluate(devset=devset, num_threads=1, display_progress=True, display_table=5)

# below code will check the accuracy code before optimizing
prev_score=evaluation(uncompiled, metric=validate_answer)

# get the accuracy after optimizing
improved_score=evaluation(compiled, metric=validate_answer)

100%|██████████| 20/20 [00:00<00:00, 748.72it/s]

Average Metric: 0 / 5  (0.0): 100%|██████████| 5/5 [00:00<00:00, 1684.59it/s]

Average Metric: 0 / 5  (0.0): 100%|██████████| 5/5 [00:00<00:00, 669.89it/s]

#### Create GPT labeled examples after compiling

In [39]:
def create_json_append_to_df(job_posting):
    # Generate answer from DSPy
    pred = compiled(context=job_posting) # before, I used uncomplied(), now I changed it to compiled(). All the rest stays the same
    posting = pred.answer

    # Extract the JSON object from the posting
    start_index = posting.find('{')
    end_index = posting.find('}', start_index) + 1

    if start_index == -1 or end_index == -1:
        print("No valid JSON object found in the posting")
        return None

    json_string = posting[start_index:end_index]

    try:
        job_details = json.loads(json_string)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return None

    # print(job_details)

    pred_json = json.dumps(job_details, indent=4)
    print('Done, Output Succeed')
    # print(pred_json)

    return pred_json

examples_json=dev_examples.copy()
examples_json['pred_json_after_compiling']=examples_json['body'].apply(lambda x: create_json_append_to_df(x))
print(examples_json.shape)
display(examples_json.tail(5))

Done, Output Succeed
Done, Output Succeed
Done, Output Succeed
Done, Output Succeed
Done, Output Succeed
Done, Output Succeed
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44873, Requested 17570. Please try again in 2.443s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44489, Requested 17570. Please try again in 2.059s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42874, Requested 17570. Please try again in 444ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.7 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50686, Requested 17572. Please try again in 8.258s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49833, Requested 17572. Please try again in 7.405s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.6 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48004, Requested 17572. Please try again in 5.576s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47062, Requested 17572. Please try again in 4.634s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.1 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53240, Requested 17603. Please try again in 10.843s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.1 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53012, Requested 17603. Please try again in 10.615s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51905, Requested 17603. Please try again in 9.508s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.1 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 6.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49725, Requested 17603. Please try again in 7.328s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.1 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43451, Requested 17603. Please try again in 1.054s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.5 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52665, Requested 17527. Please try again in 10.192s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.5 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51988, Requested 17527. Please try again in 9.515s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50887, Requested 17527. Please try again in 8.414s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50364, Requested 17527. Please try again in 7.891s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 11.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48447, Requested 17527. Please try again in 5.974s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 11.1 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47781, Requested 17572. Please try again in 5.353s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.1 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47600, Requested 17572. Please try again in 5.172s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.2 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46244, Requested 17572. Please try again in 3.816s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45596, Requested 17572. Please try again in 3.168s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.1 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44346, Requested 17572. Please try again in 1.917s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.2 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48069, Requested 17686. Please try again in 5.755s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47733, Requested 17686. Please try again in 5.419s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47402, Requested 17686. Please try again in 5.088s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.9 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43302, Requested 17686. Please try again in 988ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.7 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51895, Requested 17236. Please try again in 9.131s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.4 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51325, Requested 17236. Please try again in 8.561s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50807, Requested 17236. Please try again in 8.043s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.6 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 5.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50031, Requested 17236. Please try again in 7.267s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.5 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 7.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44338, Requested 17236. Please try again in 1.574s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.7 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48793, Requested 17267. Please try again in 6.06s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48416, Requested 17267. Please try again in 5.683s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.5 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46816, Requested 17267. Please try again in 4.083s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.8 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 7.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42840, Requested 17267. Please try again in 107ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.7 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45813, Requested 17189. Please try again in 3.002s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44909, Requested 17189. Please try again in 2.098s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43833, Requested 17189. Please try again in 1.022s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.1 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43627, Requested 17189. Please try again in 816ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.6 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52322, Requested 17219. Please try again in 9.541s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51397, Requested 17219. Please try again in 8.616s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.1 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50114, Requested 17219. Please try again in 7.333s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.9 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 5.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47100, Requested 17219. Please try again in 4.319s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51970, Requested 17648. Please try again in 9.618s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.9 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50934, Requested 17648. Please try again in 8.582s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49420, Requested 17648. Please try again in 7.068s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 5.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47937, Requested 17648. Please try again in 5.585s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.3 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 14.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42503, Requested 17648. Please try again in 151ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 14.1 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51242, Requested 17206. Please try again in 8.448s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50334, Requested 17206. Please try again in 7.54s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49831, Requested 17206. Please try again in 7.037s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.3 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47384, Requested 17206. Please try again in 4.59s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.5 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 10.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44670, Requested 17206. Please try again in 1.876s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 10.2 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44563, Requested 17192. Please try again in 1.755s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43916, Requested 17192. Please try again in 1.108s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.7 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 54091, Requested 17223. Please try again in 11.314s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.0 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53812, Requested 17223. Please try again in 11.035s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53340, Requested 17223. Please try again in 10.563s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.3 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 6.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52824, Requested 17223. Please try again in 10.047s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.4 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 15.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46221, Requested 17223. Please try again in 3.444s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.2 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52233, Requested 17279. Please try again in 9.512s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51784, Requested 17279. Please try again in 9.063s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.7 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49904, Requested 17279. Please try again in 7.183s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47389, Requested 17279. Please try again in 4.668s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.5 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43700, Requested 17279. Please try again in 979ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.3 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47244, Requested 17368. Please try again in 4.612s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46861, Requested 17368. Please try again in 4.229s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46034, Requested 17368. Please try again in 3.402s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.8 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52039, Requested 17505. Please try again in 9.544s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51125, Requested 17505. Please try again in 8.63s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.7 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49252, Requested 17505. Please try again in 6.757s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45751, Requested 17505. Please try again in 3.256s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 9.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42550, Requested 17505. Please try again in 55ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 9.3 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42975, Requested 17175. Please try again in 150ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.0 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53052, Requested 17214. Please try again in 10.266s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52618, Requested 17214. Please try again in 9.832s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52407, Requested 17214. Please try again in 9.621s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.2 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 5.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51042, Requested 17214. Please try again in 8.256s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.4 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 10.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45322, Requested 17214. Please try again in 2.536s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 10.3 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45119, Requested 17612. Please try again in 2.731s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.6 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44376, Requested 17612. Please try again in 1.988s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43143, Requested 17612. Please try again in 755ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42576, Requested 17612. Please try again in 188ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.9 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49253, Requested 17514. Please try again in 6.767s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.1 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49042, Requested 17514. Please try again in 6.556s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47529, Requested 17514. Please try again in 5.043s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.0 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 5.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45389, Requested 17514. Please try again in 2.903s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49524, Requested 17701. Please try again in 7.225s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49132, Requested 17701. Please try again in 6.833s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48109, Requested 17701. Please try again in 5.81s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 7.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47134, Requested 17701. Please try again in 4.835s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.1 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50288, Requested 17107. Please try again in 7.395s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49627, Requested 17107. Please try again in 6.734s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.2 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48254, Requested 17107. Please try again in 5.361s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.6 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 5.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44501, Requested 17107. Please try again in 1.608s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51373, Requested 17139. Please try again in 8.512s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50383, Requested 17139. Please try again in 7.521s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48913, Requested 17139. Please try again in 6.052s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.1 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 6.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48689, Requested 17139. Please try again in 5.828s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.6 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52799, Requested 17071. Please try again in 9.87s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 1.0 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51671, Requested 17071. Please try again in 8.742s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51106, Requested 17071. Please try again in 8.177s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48522, Requested 17071. Please try again in 5.593s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53693, Requested 17103. Please try again in 10.796s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53217, Requested 17103. Please try again in 10.32s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51738, Requested 17103. Please try again in 8.841s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.2 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 6.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50414, Requested 17103. Please try again in 7.517s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.9 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 11.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43416, Requested 17103. Please try again in 519ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 11.6 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52173, Requested 17654. Please try again in 9.827s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51665, Requested 17654. Please try again in 9.319s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51062, Requested 17654. Please try again in 8.716s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.7 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48245, Requested 17654. Please try again in 5.899s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 15.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47023, Requested 17654. Please try again in 4.677s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.3 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43377, Requested 17692. Please try again in 1.069s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42465, Requested 17692. Please try again in 157ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52856, Requested 16833. Please try again in 9.689s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.6 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52141, Requested 16833. Please try again in 8.974s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.1 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51901, Requested 16833. Please try again in 8.734s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51236, Requested 16833. Please try again in 8.069s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.7 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48373, Requested 16833. Please try again in 5.206s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.9 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 15.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46262, Requested 16833. Please try again in 3.095s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.4 seconds after 6 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52864, Requested 17167. Please try again in 10.031s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.2 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52489, Requested 17167. Please try again in 9.656s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51040, Requested 17167. Please try again in 8.207s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.0 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47894, Requested 17167. Please try again in 5.061s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.2 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 15.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45596, Requested 17167. Please try again in 2.763s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.3 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49283, Requested 17449. Please try again in 6.732s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 1.0 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48117, Requested 17449. Please try again in 5.566s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.6 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47348, Requested 17449. Please try again in 4.797s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.2 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44028, Requested 17449. Please try again in 1.477s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.4 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48815, Requested 17480. Please try again in 6.295s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48148, Requested 17480. Please try again in 5.628s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.6 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46424, Requested 17480. Please try again in 3.903s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45842, Requested 17480. Please try again in 3.322s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 13.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42752, Requested 17480. Please try again in 232ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 13.2 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49941, Requested 16750. Please try again in 6.691s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.1 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49734, Requested 16750. Please try again in 6.484s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48224, Requested 16750. Please try again in 4.974s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.9 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 7.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46178, Requested 16750. Please try again in 2.928s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.4 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50599, Requested 16782. Please try again in 7.381s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49753, Requested 16782. Please try again in 6.535s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48608, Requested 16782. Please try again in 5.39s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 6.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47698, Requested 16782. Please try again in 4.48s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52315, Requested 17479. Please try again in 9.794s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51503, Requested 17479. Please try again in 8.982s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.3 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 1.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50122, Requested 17479. Please try again in 7.601s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.4 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 7.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48459, Requested 17479. Please try again in 5.938s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.6 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52950, Requested 17510. Please try again in 10.46s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52271, Requested 17510. Please try again in 9.781s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.9 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50211, Requested 17510. Please try again in 7.721s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.0 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47056, Requested 17510. Please try again in 4.566s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 15.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43929, Requested 17510. Please try again in 1.439s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.9 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49618, Requested 17544. Please try again in 7.162s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.7 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48821, Requested 17544. Please try again in 6.365s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47689, Requested 17544. Please try again in 5.233s. Visit https://platform.openai.com/account/rate-limits to learn more.)
INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47524, Requested 17544. Please try again in 5.068s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.0 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Backing off 1.0 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 7.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46330, Requested 17544. Please try again in 3.873s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 7.5 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49281, Requested 17235. Please try again in 6.516s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 1.0 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48159, Requested 17235. Please try again in 5.394s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47244, Requested 17235. Please try again in 4.479s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46903, Requested 17235. Please try again in 4.138s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.4 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 14.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43312, Requested 17235. Please try again in 547ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 14.5 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51255, Requested 17632. Please try again in 8.887s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50191, Requested 17632. Please try again in 7.822s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.1 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48904, Requested 17632. Please try again in 6.536s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48582, Requested 17632. Please try again in 6.214s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 11.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46670, Requested 17632. Please try again in 4.302s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 11.0 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45842, Requested 17325. Please try again in 3.167s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 2.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45405, Requested 17325. Please try again in 2.73s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43301, Requested 17325. Please try again in 626ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.6 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51587, Requested 17363. Please try again in 8.95s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50547, Requested 17363. Please try again in 7.91s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.9 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49479, Requested 17363. Please try again in 6.842s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.9 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46474, Requested 17363. Please try again in 3.837s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.9 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 11.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 44449, Requested 17363. Please try again in 1.812s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 11.9 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43270, Requested 17380. Please try again in 650ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.4 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.4s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42697, Requested 17380. Please try again in 77ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.4 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 54502, Requested 17418. Please try again in 11.92s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 2.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 53502, Requested 17418. Please try again in 10.92s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 2.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51408, Requested 17418. Please try again in 8.826s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.7 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49511, Requested 17418. Please try again in 6.929s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.2 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 14.7s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46114, Requested 17418. Please try again in 3.532s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 14.7 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 52299, Requested 17800. Please try again in 10.099s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51389, Requested 17800. Please try again in 9.189s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 3.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50722, Requested 17800. Please try again in 8.522s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.1 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 4.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47475, Requested 17800. Please try again in 5.275s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 4.6 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 15.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 42741, Requested 17800. Please try again in 541ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.6 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}
Done, Output Succeed

INFO:backoff:Backing off request(...) for 0.1s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 49209, Requested 16848. Please try again in 6.057s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.1 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.0s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48978, Requested 16848. Please try again in 5.826s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.0 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 3.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47792, Requested 16848. Please try again in 4.64s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 3.8 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 5.6s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 43755, Requested 16848. Please try again in 603ms. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 5.6 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.3s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47692, Requested 17327. Please try again in 5.019s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Done, Output Succeed
Backing off 0.3 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 47201, Requested 17327. Please try again in 4.528s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.5s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46295, Requested 17327. Please try again in 3.622s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.5 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 6.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45639, Requested 17327. Please try again in 2.966s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 6.8 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 400}

INFO:backoff:Backing off request(...) for 0.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 51095, Requested 17358. Please try again in 8.453s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.8 seconds after 1 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.8s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 50139, Requested 17358. Please try again in 7.497s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.8 seconds after 2 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 1.9s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 48228, Requested 17358. Please try again in 5.586s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 1.9 seconds after 3 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 0.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 46192, Requested 17358. Please try again in 3.55s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 0.2 seconds after 4 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}

INFO:backoff:Backing off request(...) for 15.2s (openai.error.RateLimitError: Rate limit reached for gpt-3.5-turbo in organization org-LnLUOX2GedQp7zTstR5xBRKj on tokens per min (TPM): Limit 60000, Used 45909, Requested 17358. Please try again in 3.267s. Visit https://platform.openai.com/account/rate-limits to learn more.)

Backing off 15.2 seconds after 5 tries calling function <function GPT3.request at 0x10c162290> with kwargs {'max_tokens': 200, 'n': 1, 'temperature': 0.0}
Done, Output Succeed
(46, 17)

                     id                 body  min_edulevels_name employment_type_name  min_years_experience remote_type_name  salary_to           city_name     state_name           title_name specialized_skills_name  certifications_name   common_skills_name          naics2_name            onet_name            pred_json pred_json_after_compiling
41  1f9b129547a8bc90...  Logistics Coordi...  High school or GED  Full-time (> 32 ...                  NaN            [None]    29120.0       Henderson, NV         Nevada  Logistics Coordi...  ['Continuous Imp...                      []  ['Management', '...  Unclassified Ind...         Logisticians  {\n    "position...  {\n    "position...
42  a12030480f74113b...  Systems Administ...   Bachelor's degree  Full-time (> 32 ...                  3.0            [None]        NaN          Laurel, MD       Maryland  Systems and Secu...  ['Traceability M...     ['CompTIA Securi...  ['Research', 'In...  Unclassified Ind...  Network and Comp...  {\n    "position...  {\n    "position...
43  d5cd5a4da6da14dc...  Between $52,250 ...   Bachelor's degree  Full-time (> 32 ...                  6.0            [None]    78390.0  Jefferson City, MO       Missouri    Technical Writers  ['Copy Editing',...                      []  ['Customer Servi...  Unclassified Ind...    Technical Writers  {\n    "position...  {\n    "position...
44  b7e2dc5d319e8a5a...  Sr. Net Develope...   Bachelor's degree  Full-time (> 32 ...                  2.0            [None]        NaN          Irving, TX          Texas      .NET Developers  ['Code Review', ...                      []       ['Operations']  Unclassified Ind...  Software Developers  {\n    "position...  {\n    "position...
45  9c61f7202efc3e92...  Federal Sales En...   Bachelor's degree  Full-time (> 32 ...                  NaN            Remote   120000.0         Walpole, MA  Massachusetts  Federal Sales En...  ['Sales Forecast...     ['Product Certif...            ['Sales']  Unclassified Ind...      Sales Engineers  {\n    "position...  {\n    "position...

In [43]:
examples_json_with_manual_labels=examples_json.copy()
merged_df = pd.merge(examples_json,train_examples[['id', 'pred_json']], on='id', how='left')
merged_df.rename(columns={'pred_json': 'manual_labeling'}, inplace=True)

merged_df.head(3)

                    id                 body  min_edulevels_name employment_type_name  min_years_experience remote_type_name  salary_to        city_name      state_name           title_name specialized_skills_name  certifications_name   common_skills_name          naics2_name            onet_name          pred_json_x pred_json_after_compiling          pred_json_y
0  18ec1d38a8acc34f...  Derrickhand, Buc...  High school or GED  Full-time (> 32 ...                  1.0            [None]        NaN   Buckhannon, WV   West Virginia         Derrickhands  ['Well Services'...     ['CDL Class B Li...  ['Customer Servi...  Unclassified Ind...  Roustabouts, Oil...  {\n    "position...  {\n    "position...       {\n    "position...
1  0b8c421fca565f14...  Business Relatio...  High school or GED  Full-time (> 32 ...                  4.0            [None]    45000.0   Mount Airy, NC  North Carolina  Business Relatio...  ['Public Adminis...                      []  ['Presentations'...  Unclassified Ind...  Rehabilitation C...  {\n    "position...  {\n    "position...                       NaN
2  256704ef9f689ef8...  Pharmacy Technic...  High school or GED  Full-time (> 32 ...                  NaN            [None]    39520.0  San Quentin, CA      California  Pharmacy Technic...  ['Medical Prescr...     ['Certified Phar...  ['Customer Servi...  Unclassified Ind...  Pharmacy Technic...  {\n    "position...  {\n    "position...       {\n    "position...